### PR TITLE
Rails 4.2 upgrade

### PR DESCRIPTION
**Pull request by dometto**
Not mergeable yet, but results are not bad. Getting 8 spec failures of this form:

```
ActiveRecord::RecordNotFound:
       Couldn't find all Roles with 'id': (first, {:conditions=>{:title=>:admin, :resource_id=>nil}}) [WHERE "roles"."user_id" = ?] (found 0 results, but was looking for 2)
```

This is because `find(:all, {:conditions ...})` has been deprecated in Rails 4.

Furthermore, I had to add the `protected_attributes` gem for now. See e.g. http://www.sitepoint.com/rails-4-quick-look-strong-parameters/

Also upgraded rspec, which complains that we should use the `:expect` rather than the `:should` syntax.

### CODE REVIEW

**Comment by dometto** [comment]
specs passing, no more deprecation warnings. All systems go for development, but we should mind that `activerecord-jdbc-adapter` is not production ready with rails 4.2:
https://github.com/jruby/activerecord-jdbc-adapter/issues/599

**Comment by bartkamphorst** [comment]
Exciting! I have a bunch of local changes that will no doubt conflict with this PR, but I'll figure that out later this week. Go for it!

**Comment by dometto** [comment]
Done! Hope the manual merging isn't too bad :)

**Comment by Ch4s3** [comment]
@dometto You should hop on the bounty https://www.bountysource.com/issues/5831191-tasks-to-finish-4-2-support

**Pull request merged**
